namespace :wc do
  desc "Import placeholders required for inserting variable value into texts"
  task :import_placeholders => :environment do

    Placeholder.destroy_all
    Placeholder.create!([
      {name: "{event.bottom_text}", description: "Text am Ende der Seminaranzeige. Gut geeignet für Impressum u.ä.", localisation_type: 0, account_id: 1, sortorder: 1, objecttype: "event", display_name: "bottom_text"},
      {name: "{event.city}", description: "Stadt des Veranstaltungsortes", localisation_type: 0, account_id: 1, sortorder: 11, objecttype: "event", display_name: "city"},
      {name: "{event.country}", description: "Land des Veranstaltungsortes", localisation_type: 0, account_id: 1, sortorder: 21, objecttype: "event", display_name: "country"},
      {name: "{event.duration}", description: "Dauer der Veranstaltung", localisation_type: 0, account_id: 1, sortorder: 31, objecttype: "event", display_name: "duration"},
      {name: "{event.early_signup_deadline_day}", description: nil, localisation_type: 0, account_id: 1, sortorder: 41, objecttype: "event", display_name: "early_signup_deadline_day"},
      {name: "{event.early_signup_deadline_hours}", description: nil, localisation_type: 0, account_id: 1, sortorder: 51, objecttype: "event", display_name: "early_signup_deadline_hours"},
      {name: "{event.early_signup_deadline_minutes}", description: nil, localisation_type: 0, account_id: 1, sortorder: 61, objecttype: "event", display_name: "early_signup_deadline_minutes"},
      {name: "{event.early_signup_deadline_month}", description: nil, localisation_type: 0, account_id: 1, sortorder: 71, objecttype: "event", display_name: "early_signup_deadline_month"},
      {name: "{event.early_signup_deadline_year}", description: nil, localisation_type: 0, account_id: 1, sortorder: 81, objecttype: "event", display_name: "early_signup_deadline_year"},
      {name: "{event.early_signup_deadline}", description: "", localisation_type: 1, account_id: 1, sortorder: 91, objecttype: "event", display_name: "early_signup_deadline"},
      {name: "{event.end_date_day}", description: nil, localisation_type: 0, account_id: 1, sortorder: 101, objecttype: "event", display_name: "end_date_day"},
      {name: "{event.end_date_hours}", description: nil, localisation_type: 0, account_id: 1, sortorder: 111, objecttype: "event", display_name: "end_date_hours"},
      {name: "{event.end_date_minutes}", description: nil, localisation_type: 0, account_id: 1, sortorder: 121, objecttype: "event", display_name: "end_date_minutes"},
      {name: "{event.end_date_month}", description: nil, localisation_type: 0, account_id: 1, sortorder: 131, objecttype: "event", display_name: "end_date_month"},
      {name: "{event.end_date_year}", description: nil, localisation_type: 0, account_id: 1, sortorder: 141, objecttype: "event", display_name: "end_date_year"},
      {name: "{event.end_date}", description: "", localisation_type: 1, account_id: 1, sortorder: 151, objecttype: "event", display_name: "end_date"},
      {name: "{event.external_signup_text}", description: nil, localisation_type: 0, account_id: 1, sortorder: 171, objecttype: "event", display_name: "external_signup_text"},
      {name: "{event.external_signup_url}", description: nil, localisation_type: 0, account_id: 1, sortorder: 181, objecttype: "event", display_name: "external_signup_url"},
      {name: "{event.googlemapslocation}", description: nil, localisation_type: 0, account_id: 1, sortorder: 191, objecttype: "event", display_name: "googlemapslocation"},
      {name: "{event.latest_signup_date_day}", description: nil, localisation_type: 0, account_id: 1, sortorder: 201, objecttype: "event", display_name: "latest_signup_date_day"},
      {name: "{event.latest_signup_date_hours}", description: nil, localisation_type: 0, account_id: 1, sortorder: 211, objecttype: "event", display_name: "latest_signup_date_hours"},
      {name: "{event.latest_signup_date_minutes}", description: nil, localisation_type: 0, account_id: 1, sortorder: 221, objecttype: "event", display_name: "latest_signup_date_minutes"},
      {name: "{event.latest_signup_date_month}", description: nil, localisation_type: 0, account_id: 1, sortorder: 231, objecttype: "event", display_name: "latest_signup_date_month"},
      {name: "{event.latest_signup_date_year}", description: nil, localisation_type: 0, account_id: 1, sortorder: 241, objecttype: "event", display_name: "latest_signup_date_year"},
      {name: "{event.latest_signup_date}", description: "", localisation_type: 1, account_id: 1, sortorder: 251, objecttype: "event", display_name: "latest_signup_date"},
      {name: "{event.location}", description: nil, localisation_type: 0, account_id: 1, sortorder: 261, objecttype: "event", display_name: "location"},
      {name: "{event.longdescription}", description: nil, localisation_type: 0, account_id: 1, sortorder: 271, objecttype: "event", display_name: "longdescription"},
      {name: "{event.maxparticipants}", description: nil, localisation_type: 0, account_id: 1, sortorder: 281, objecttype: "event", display_name: "maxparticipants"},
      {name: "{event.name}", description: nil, localisation_type: 0, account_id: 1, sortorder: 291, objecttype: "event", display_name: "name"},
      {name: "{event.price_early_signup}", description: "", localisation_type: 2, account_id: 1, sortorder: 301, objecttype: "event", display_name: "price_early_signup"},
      {name: "{event.price}", description: "", localisation_type: 2, account_id: 1, sortorder: 311, objecttype: "event", display_name: "price"},
      {name: "{event.reservation_expiry_day}", description: nil, localisation_type: 0, account_id: 1, sortorder: 321, objecttype: "event", display_name: "reservation_expiry_day"},
      {name: "{event.reservation_expiry_hours}", description: nil, localisation_type: 0, account_id: 1, sortorder: 331, objecttype: "event", display_name: "reservation_expiry_hours"},
      {name: "{event.reservation_expiry_minutes}", description: nil, localisation_type: 0, account_id: 1, sortorder: 341, objecttype: "event", display_name: "reservation_expiry_minutes"},
      {name: "{event.reservation_expiry_month}", description: nil, localisation_type: 0, account_id: 1, sortorder: 351, objecttype: "event", display_name: "reservation_expiry_month"},
      {name: "{event.reservation_expiry_year}", description: nil, localisation_type: 0, account_id: 1, sortorder: 361, objecttype: "event", display_name: "reservation_expiry_year"},
      {name: "{event.reservation_expiry}", description: "", localisation_type: 1, account_id: 1, sortorder: 371, objecttype: "event", display_name: "reservation_expiry"},
      {name: "{event.shortdescription}", description: nil, localisation_type: 0, account_id: 1, sortorder: 381, objecttype: "event", display_name: "shortdescription"},
      {name: "{event.start_date_day}", description: nil, localisation_type: 0, account_id: 1, sortorder: 391, objecttype: "event", display_name: "start_date_day"},
      {name: "{event.start_date_hours}", description: nil, localisation_type: 0, account_id: 1, sortorder: 401, objecttype: "event", display_name: "start_date_hours"},
      {name: "{event.start_date_minutes}", description: nil, localisation_type: 0, account_id: 1, sortorder: 411, objecttype: "event", display_name: "start_date_minutes"},
      {name: "{event.start_date_month}", description: nil, localisation_type: 0, account_id: 1, sortorder: 421, objecttype: "event", display_name: "start_date_month"},
      {name: "{event.start_date_year}", description: nil, localisation_type: 0, account_id: 1, sortorder: 431, objecttype: "event", display_name: "start_date_year"},
      {name: "{event.start_date}", description: "", localisation_type: 1, account_id: 1, sortorder: 441, objecttype: "event", display_name: "start_date"},
      {name: "{event.start_time}", description: nil, localisation_type: 0, account_id: 1, sortorder: 451, objecttype: "event", display_name: "start_time"},
      {name: "{event.start_time_with_timezone}", description: "Uhrzeit, an der die Veranstaltung beginnt.", localisation_type: 0, account_id: nil, sortorder: 162, objecttype: "event", display_name: "start_time_with_timezone"},
      {name: "{event.street}", description: nil, localisation_type: 0, account_id: 1, sortorder: 461, objecttype: "event", display_name: "street"},
      {name: "{event.streetno}", description: nil, localisation_type: 0, account_id: 1, sortorder: 471, objecttype: "event", display_name: "streetno"},
      {name: "{event.zip}", description: nil, localisation_type: 0, account_id: 1, sortorder: 481, objecttype: "event", display_name: "zip"},
      {name: "{eventbooking.booking_date_day}", description: nil, localisation_type: 0, account_id: 1, sortorder: 491, objecttype: "eventbooking", display_name: "booking_date_day"},
      {name: "{eventbooking.booking_date_hours}", description: nil, localisation_type: 0, account_id: 1, sortorder: 501, objecttype: "eventbooking", display_name: "booking_date_hours"},
      {name: "{eventbooking.booking_date_minutes}", description: nil, localisation_type: 0, account_id: 1, sortorder: 511, objecttype: "eventbooking", display_name: "booking_date_minutes"},
      {name: "{eventbooking.booking_date_month}", description: nil, localisation_type: 0, account_id: 1, sortorder: 492, objecttype: "eventbooking", display_name: "booking_date_month"},
      {name: "{eventbooking.booking_date_year}", description: nil, localisation_type: 0, account_id: 1, sortorder: 493, objecttype: "eventbooking", display_name: "booking_date_year"},
      {name: "{eventbooking.booking_date}", description: "", localisation_type: 1, account_id: 1, sortorder: 490, objecttype: "eventbooking", display_name: "booking_date"},
      {name: "{eventbooking.city}", description: nil, localisation_type: 0, account_id: 1, sortorder: 551, objecttype: "eventbooking", display_name: "city"},
      {name: "{eventbooking.company}", description: nil, localisation_type: 0, account_id: 1, sortorder: 561, objecttype: "eventbooking", display_name: "company"},
      {name: "{eventbooking.country}", description: nil, localisation_type: 0, account_id: 1, sortorder: 571, objecttype: "eventbooking", display_name: "country"},
      {name: "{eventbooking.email}", description: nil, localisation_type: 0, account_id: 1, sortorder: 581, objecttype: "eventbooking", display_name: "email"},
      {name: "{eventbooking.firstname}", description: nil, localisation_type: 0, account_id: 1, sortorder: 591, objecttype: "eventbooking", display_name: "firstname"},
      {name: "{eventbooking.gender_direct}", description: nil, localisation_type: 0, account_id: 1, sortorder: 601, objecttype: "eventbooking", display_name: "gender_direct"},
      {name: "{eventbooking.gender_indirect}", description: nil, localisation_type: 0, account_id: 1, sortorder: 611, objecttype: "eventbooking", display_name: "gender_indirect"},
      {name: "{eventbooking.gender}", description: nil, localisation_type: 0, account_id: 1, sortorder: 621, objecttype: "eventbooking", display_name: "gender"},
      {name: "{eventbooking.lastname}", description: nil, localisation_type: 0, account_id: 1, sortorder: 631, objecttype: "eventbooking", display_name: "lastname"},
      {name: "{eventbooking.salutation}", description: nil, localisation_type: 0, account_id: 1, sortorder: 641, objecttype: "eventbooking", display_name: "salutation"},
      {name: "{eventbooking.street_no}", description: nil, localisation_type: 0, account_id: 1, sortorder: 651, objecttype: "eventbooking", display_name: "street_no"},
      {name: "{eventbooking.street}", description: nil, localisation_type: 0, account_id: 1, sortorder: 661, objecttype: "eventbooking", display_name: "street"},
      {name: "{eventbooking.tel}", description: nil, localisation_type: 0, account_id: 1, sortorder: 671, objecttype: "eventbooking", display_name: "tel"},
      {name: "{eventbooking.zip}", description: nil, localisation_type: 0, account_id: 1, sortorder: 681, objecttype: "eventbooking", display_name: "zip"},
      {name: "{invoice.due_date}", description: "Your invoice's due date", localisation_type: 1, account_id: 1, sortorder: 691, objecttype: "invoice", display_name: "due_date"},
      {name: "{request.firstname}", description: nil, localisation_type: 0, account_id: 1, sortorder: 711, objecttype: "request", display_name: "firstname"},
      {name: "{request.lastname}", description: nil, localisation_type: 0, account_id: 1, sortorder: 731, objecttype: "request", display_name: "lastname"},
      {name: "{request.gender}", description: nil, localisation_type: 0, account_id: 1, sortorder: 721, objecttype: "request", display_name: "gender"},
      {name: "{request.email}", description: nil, localisation_type: 0, account_id: 1, sortorder: 701, objecttype: "request", display_name: "email"},
      {name: "{request.tel}", description: nil, localisation_type: 0, account_id: 1, sortorder: 751, objecttype: "request", display_name: "tel"},
      {name: "{request.message}", description: nil, localisation_type: 0, account_id: 1, sortorder: 741, objecttype: "request", display_name: "message"},
      {name: "{event.end_time}", description: "Uhrzeit, an der die Veranstaltung endet.", localisation_type: 0, account_id: nil, sortorder: 161, objecttype: "event", display_name: "end_time"},
      {name: "{event.end_time_with_timezone}", description: "Uhrzeit, an der die Veranstaltung endet.", localisation_type: 0, account_id: nil, sortorder: 162, objecttype: "event", display_name: "end_time_with_timezone"},
      {name: "{event.durationunit}", description: "Einheit der Veranstaltungsdauer, z.B. Stunden", localisation_type: 0, account_id: nil, sortorder: 33, objecttype: "event", display_name: "durationunit"}
    ])


  end
end
